src/TVHome/src/Entity/OrderItem.php
<?php

namespace App\Entity;

use App\Repository\OrderItemRepository;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

#[ORM\Entity(repositoryClass: OrderItemRepository::class)]
class OrderItem
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\ManyToOne(inversedBy: 'OderItem')]
    private ?Product $Product = null;

    #[ORM\Column]
    #[Assert\NotBlank]
    #[Assert\GreaterThanOrEqual(1)]
    private ?int $Quantity = null;

    #[ORM\ManyToOne(targetEntity: Order::class, inversedBy: 'item')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Order $Ordered = null;

    #[ORM\ManyToOne(inversedBy: 'Item')]
    private ?OrderCart $orderCart = null;

    #[ORM\ManyToOne(inversedBy: 'Item')]
    #[ORM\JoinColumn(nullable: false)]
    private ?OrderCart $OrderRef = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getProduct(): ?Product
    {
        return $this->Product;
    }

    public function setProduct(?Product $Product): static
    {
        $this->Product = $Product;

        return $this;
    }

    public function getQuantity(): ?int
    {
        return $this->Quantity;
    }

    public function setQuantity(int $Quantity): static
    {
        $this->Quantity = $Quantity;

        return $this;
    }

    public function getOrdered(): ?Order
    {
        return $this->Ordered;
    }

    public function setOrdered(?Order $Ordered): self
    {
        $this->Ordered = $Ordered;

        return $this;
    }

    /**
     * Kiểm tra xem mặt hàng đã cho có tương ứng với mặt hàng tương tự hay không.
     *
     * @param OrderItem $item
     *
     * @return bool
     */
    public function equals(OrderItem $item): bool
    {
        return $this->getProduct()->getId() === $item->getProduct()->getId();
    }

    /**
     * Tính tổng tiền.
     *
     * @return float|int
     */
    public function getTotal(): float
    {
        return $this->getProduct()->getPrice() * $this->getQuantity();
    }

    public function getOrderCart(): ?OrderCart
    {
        return $this->orderCart;
    }

    public function setOrderCart(?OrderCart $orderCart): static
    {
        $this->orderCart = $orderCart;

        return $this;
    }

    public function getOrderRef(): ?OrderCart
    {
        return $this->OrderRef;
    }

    public function setOrderRef(?OrderCart $OrderRef): static
    {
        $this->OrderRef = $OrderRef;

        return $this;
    }
}

src/TVHome/src/Entity/Product.php
<?php

namespace App\Entity;

use App\Repository\ProductRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: ProductRepository::class)]
class Product
{
    #[ORM\Id]
    //#[ORM\GeneratedValue]
    #[ORM\Column]

    private ?string $id = null;

    #[ORM\Column(length: 255)]
    private ?string $name = null;

    #[ORM\Column(length: 255)]
    private ?string $image = null;

    #[ORM\Column(length: 255)]
    private ?string $description = null;

    #[ORM\Column(length: 10)]
    private ?int $price = null;

    #[ORM\OneToMany(mappedBy: 'Product', targetEntity: OrderItem::class)]
    private Collection $OderItem;

    #[ORM\Column]
    private ?int $Quantity = null;

    public function __construct()
    {
        $this->OderItem = new ArrayCollection();
    }

    public function getId(): ?string
    {
        return $this->id;
    }

    public function setId(string $id): static
    {
        $this->id = $id;

        return $this;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): static
    {
        $this->name = $name;

        return $this;
    }

    public function getImage(): ?string
    {
        return $this->image;
    }

    public function setImage(string $image): static
    {
        $this->image = $image;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): static
    {
        $this->description = $description;

        return $this;
    }

    public function getPrice(): ?int
    {
        return $this->price;
    }

    public function setPrice(int $price): static
    {
        $this->price = $price;

        return $this;
    }

    /**
     * @return Collection<int, OrderItem>
     */
    public function getOderItem(): Collection
    {
        return $this->OderItem;
    }

    public function addOderItem(OrderItem $oderItem): static
    {
        if (!$this->OderItem->contains($oderItem)) {
            $this->OderItem->add($oderItem);
            $oderItem->setProduct($this);
        }

        return $this;
    }

    public function removeOderItem(OrderItem $oderItem): static
    {
        if ($this->OderItem->removeElement($oderItem)) {
            // set the owning side to null (unless already changed)
            if ($oderItem->getProduct() === $this) {
                $oderItem->setProduct(null);
            }
        }

        return $this;
    }

    public function getQuantity(): ?int
    {
        return $this->Quantity;
    }

    public function setQuantity(int $Quantity): static
    {
        $this->Quantity = $Quantity;

        return $this;
    }
}

src/TVHome/src/Entity/User.php
<?php

namespace App\Entity;

use App\Repository\UserRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;
use Symfony\Component\Security\Core\User\UserInterface;
use Symfony\Component\Uid\Uuid;

#[ORM\Entity(repositoryClass: UserRepository::class)]
#[UniqueEntity(fields: ['username'], message: 'Tên người dùng đã được sử dụng !')]


class User implements UserInterface, PasswordAuthenticatedUserInterface
{
    #[ORM\Id]
    #[ORM\GeneratedValue(strategy: 'CUSTOM')]
    #[ORM\Column(type:'uuid', unique:true)]
    #[ORM\CustomIdGenerator(class: 'doctrine.uuid_generator')]
    private ?Uuid $id = null;

    #[ORM\Column(unique: true)]
    private ?string $username = null;

    #[ORM\Column]
    private array $roles = [];

    /**
     * @var string The hashed password
     */
    #[ORM\Column]
    private ?string $password = null;

    #[ORM\Column]
    private ?\DateTimeImmutable $created_at = null;

    #[ORM\Column(length: 10)]
    private ?string $Last_name = null;

    #[ORM\Column(length: 10)]
    private ?string $Name = null;

    /**
     * A non-persisted field that's used to create the encoded password.
     *
     * @var string
     */
    private $plainPassword;

    #[ORM\Column(length: 255)]
    private ?string $PhoneNumber = null;

    #[ORM\Column(length: 255)]
    private ?string $Address = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $Email = null;

    #[ORM\Column(nullable: true)]
    private ?\DateTimeImmutable $updatedAt = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $Image = null;

    public function getPlainPassword()
    {
        return $this->plainPassword;
    }
    public function setPlainPassword($plainPassword)
    {
        $this->plainPassword = $plainPassword;
    }
    

    public function getId(): ?Uuid
    {
        return $this->id;
    }

    public function setId(Uuid $id): static
    {
        $this->id = $id;

        return $this;
    }

    public function getUsername(): ?string
    {
        return $this->username;
    }

    public function setUsername(string $username): static
    {
        $this->username = $username;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUserIdentifier(): string
    {
        return (string) $this->username;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    public function setRoles(array $roles): static
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see PasswordAuthenticatedUserInterface
     */
    public function getPassword(): string
    {
        return $this->password;
    }

    public function setPassword(string $password): static
    {
        $this->password = $password;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials(): void
    {
        // If you store any temporary, sensitive data on the user, clear it here
        $this->plainPassword = null;
    }


    public function getCreatedAt(): ?\DateTimeImmutable
    {
        return $this->created_at;
    }

    public function setCreatedAt(\DateTimeImmutable $created_at): static
    {
        $this->created_at = $created_at;

        return $this;
    }

    public function getLastName(): ?string
    {
        return $this->Last_name;
    }

    public function setLastName(string $Last_name): static
    {
        $this->Last_name = $Last_name;

        return $this;
    }

    public function getName(): ?string
    {
        return $this->Name;
    }

    public function setName(string $Name): static
    {
        $this->Name = $Name;

        return $this;
    }

    public function getPhoneNumber(): ?string
    {
        return $this->PhoneNumber;
    }

    public function setPhoneNumber(string $PhoneNumber): static
    {
        $this->PhoneNumber = $PhoneNumber;

        return $this;
    }

    public function getAddress(): ?string
    {
        return $this->Address;
    }

    public function setAddress(string $Address): static
    {
        $this->Address = $Address;

        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->Email;
    }

    public function setEmail(?string $Email): static
    {
        $this->Email = $Email;

        return $this;
    }

    public function getUpdatedAt(): ?\DateTimeImmutable
    {
        return $this->updatedAt;
    }

    public function setUpdatedAt(?\DateTimeImmutable $updatedAt): static
    {
        $this->updatedAt = $updatedAt;

        return $this;
    }

    public function getImage(): ?string
    {
        return $this->Image;
    }

    public function setImage(?string $Image): static
    {
        $this->Image = $Image;

        return $this;
    }
 
}

src/TVHome/src/Form/CartType.php
<?php

namespace App\Form;

use App\Entity\OrderCart;
use App\Form\EventListener\ClearCartListener;
use App\Form\EventListener\RemoveCartItemListener;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\CollectionType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class CartType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('item', CollectionType::class, [
                'entry_type' => CartItemType::class
            ])
            ->add('save', SubmitType::class)
            ->add('clear', SubmitType::class);
            
        $builder->addEventSubscriber(new RemoveCartItemListener());
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => OrderCart::class,
        ]);
    }
}

src/TVHome/src/Controller/CartController.php
<?php

namespace App\Controller;

use App\Form\CartType;
use App\Manager\CartManager;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class CartController extends AbstractController
{
    #[Route('/cart', name: 'cart')]
    public function index(CartManager $cartManager, Request $request): Response
    {
        $cart = $cartManager->getCurrentCart();
        $form = $this->createForm(CartType::class, $cart);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $cart->setUpdateAt(new \DateTimeImmutable());
            $cartManager->save($cart);

            return $this->redirectToRoute('cart');
        }

        return $this->render('cart/index.html.twig', [
            'cart' => $cart,
            'form' => $form->createView()
        ]);
    }
}

src/TVHome/templates/cart/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Giỏ hàng{% endblock %}

{% block body %}
<!-- Font Awesome -->
<link
  href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css"
  rel="stylesheet"
/>
<!-- Google Fonts -->
<link
  href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap"
  rel="stylesheet"
/>
<!-- MDB -->
<link
  href="https://cdnjs.cloudflare.com/ajax/libs/mdb-ui-kit/7.1.0/mdb.min.css"
  rel="stylesheet"
/>
<link rel="stylesheet" href="assets/css/main.css" />
<link rel="icon" href="assets/favicon.svg">


<body>

<!-- cart + summary -->
<section class="bg-light my-5">
  <div class="container">
    <div class="row">
      <!-- cart -->
      <div class="col-lg-14">
        <div class="card border shadow-0">
          <div class="m-4">
            <h4 class="card-title mb-4">Giỏ hàng của bạn</h4>
            {% if cart.item.count > 0 %}
            <div class="row mt-4">
              
              <div class="col-md-8">

                {{ form_start(form) }}
                <div class="card">
                    <ul class="list-group list-group-flush">
                        {% for item in form.item %}
                            <li class="list-group-item d-flex">
                                <div class="flex-fill mr-2">
                                    <img src="{{ item.vars.data.product.image }}" width="64" alt="Product image">
                                </div>
                                <div class="flex-fill mr-2">
                                    <h5 class="mt-0 mb-0">{{ item.vars.data.product.name }}</h5>
                                    <div class="col-lg col-sm-6 d-flex justify-content-sm-center justify-content-md-start justify-content-lg-center justify-content-xl-end mb-2">
                                        <div class="float-md-end">
                                            {{ form_widget(item.quantity, {
                                                'attr': {
                                                    'class': 'form-control form-control-sm ' ~ (item.quantity.vars.valid ? '' : 'is-invalid')
                                                }
                                            }) }}
                                            <div class="invalid-feedback">
                                                {{ form_errors(item.quantity) }}
                                            </div>
                                        </div>
                                        {{ form_widget(item.remove, {'attr': {'class': 'btn btn-dark btn-sm'}}) }}
                                    </div>
                                </div>
                                <div class="flex-fill mr-2 text-right">
                                    <b>{{ item.vars.data.product.price }} VND</b>
                                </div>
                            </li>
                        {% endfor %}
                    </ul>
                </div>
                {{ form_end(form, {'render_rest': false}) }}

              </div>
              
              <div class="col-md-4">

                <div class="card mt-4 mt-md-0">
                  <ul class="list-group list-group-flush">
                      <li class="list-group-item d-flex justify-content-between">
                          <div><b>Thành tiền</b></div>
                          <span><b>{{ cart.total }}</b></span>
                      </li>
                  </ul>
                  <div class="card-body">
                      <a href="/order" class="btn btn-primary w-100">Đặt hàng</a>
                      <a href="/" class="btn btn-light w-100 border mt-2"> Tiếp tục mua sắm </a>
                  </div>
                </div>

              </div>
            </div>
            {% else %}
            <div class="alert alert-info">
              Giỏ hàng của bạn đang trống. 
            </div>
            {% endif %}
          </div>
        </div>
      </div>
      <!-- cart -->
    </div>
  </div>
</section>
<!-- cart + summary -->


    <!-- MDB -->
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/mdb-ui-kit/6.4.2/mdb.min.js"></script>    
</body>
{% endblock %}